title: Ruchir Dhingra
logo: /assets/img/1690135473791.jpg
description: A candidate who is confident and has good communication skills.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
